package com.github.springbootmvcdemo.repository;

import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

import com.github.springbootmvcdemo.models.Location;

// The Location CRUD functions are generated by SPRING BOOT CrudRepository
@Repository
public interface LocationRepository extends CrudRepository<Location, String>{
    
    // https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.query-methods.at-query
    @Query("SELECT l FROM Location l WHERE l.trashed = 0 AND l.code = ?1")
    public Location findByCode(String code);

    // https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#jpa.modifying-queries
    // @Modifying queries can only use void or int/Integer as return type
    @Modifying
    @Query("UPDATE Location l SET l.trashed = 1 WHERE l.code = ?1")
    public void trashedByCode(String code);
}
